server:
  port: 8001

mybatis:
  type-aliases-package: com.fubic.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
eureka:
  client:
    service-url:
#      连接Eureka集群
#      defaultZone: http://localhost:7002/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
#      单机Eureka
      defaultZone: http://localhost:7001/eureka/

  instance:
    instance-id: springcloud-provider-dept8001 # 修改eureka上的默认描述信息

info:
  app.name: fubic-springcloud
  company.name: ali