server:
  port: 82

euraka:
  client:
    service-url:
      #      defaultZone: http://127.0.0.1:8088/eureka
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: false
    register-with-eureka: false # 不向注册中心注册自己
#      集群
#      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/

